# super user access is required
sudo: required
#install docker dependencies
services:
  - docker
# prepare the docker image
before_install:
  - docker build -t pranavj1001/docker-travis-aws-integration -f Dockerfile.dev .

script:
  - docker run pranavj1001/docker-travis-aws-integration npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-travis-aws-integration"
  env: "DockerTravisAwsIntegration-env"
  bucket_name: "elasticbeanstalk-us-east-2-087431259218"
  bucket_path: "docker-travis-aws-integration"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"