# super user access is required
sudo: required
#install docker dependencies
services:
  - docker
# prepare the docker image
before_install:
  - docker build -t pranavj1001/docker-travis-aws-integration -f Dockerfile.dev .

script:
  - docker run pranavj1001/docker-travis-aws-integration npm run test -- --converage